server:
  port: 8080

spring:
  application:
    name: colin-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    # 使用 SpringCloudLoadBalancer 时，需要禁用 ribbon
#    loadbalancer:
#      ribbon:
#        enabled: false